### ISSUE TITLE
Investigate OSBMS/OSVMS up-scaling and IP reservations

### ISSUE THREAD

**Issue by abays** [openstack-k8s-operators/osp-director-operator#297]
We currently allocate hostname/IP reservations during up-scaling before we actually know if there are resources available in the cluster to satisfy the request.  This can result in unusual states for OSNets and OSIPSets, as we have reproduced through the procedure below:
1. Deploy an OSBMS with count 1
2. Let the operator provision 1 BMH via Metal3
3. Scale the OSBMS count to 3.  Only one extra worker is free, so the OSBMS will complain that it can't reach 3 (but it will still scale 1 more, up to 2)
4. Look at the hostnames in the OSBMS's associated OSIPSet:

```
hostNameRefs:
    laborer-0: openshift-worker-3
    laborer-1: unassigned
    laborer-2: openshift-worker-4
```

Somehow it skipped laborer-1 and chose laborer-2 for the second compute.  Also, the OSNet for ctlplane has 3 non-deleted reservations for the Laborer role:

```
roleReservations:
    Laborer:
      addToPredictableIPs: true
      reservations:
      - deleted: false
        hostname: laborer-0
        ip: 192.168.25.100
        vip: false
      - deleted: false
        hostname: laborer-1
        ip: 192.168.25.101
        vip: false
      - deleted: false
        hostname: laborer-2
        ip: 192.168.25.102
        vip: false
```

**Comment by abays** [comment]
Another thing to try once it hits this state:
1. Annotate `laborer-0`/`openshift-worker-3` for deletion
2. Scale-down the OSBMS to 1
3. Wait for Metal3 operator to deprovision `openshift-worker-3` BMH
4. Scale-up the OSBMS to 2
5. Notice that `laborer-0` hostname is skipped and `laborer-1` is chosen for `openshift-worker-3` instead:

```
apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackIPSet
...
  hostCount: 2
  hostNameRefs:
    laborer-1: openshift-worker-3
    laborer-2: openshift-worker-4
   ...
```

Seems like it should have chosen `laborer-0` again, since it was deleted and therefore available:

```
apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackNet
...
  roleReservations:
    Laborer:
      addToPredictableIPs: true
      reservations:
      - deleted: true
        hostname: laborer-0
        ip: 192.168.25.100
        vip: false
        ...
```
